In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Generate Synthetic Dataset
def generate_synthetic_data(num_samples):
    np.random.seed(42)
    rainfall = np.random.uniform(0, 100, num_samples)
    atmospheric_pressure = np.random.uniform(800, 1200, num_samples)
    soil_absorption = np.random.uniform(0, 1, num_samples)
    runoff_volume = np.random.choice([0, 1], size=num_samples, p=[0.8, 0.2])

    synthetic_data = pd.DataFrame({
        'Rainfall': rainfall,
        'Atmospheric_Pressure': atmospheric_pressure,
        'Soil_Absorption': soil_absorption,
        'Runoff_Volume': runoff_volume
    })

    return synthetic_data

# Machine Learning Model
def train_model(X_train, y_train):
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)
    return model

# Evaluate Model
def evaluate_model(model, X_test, y_test):
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    confusion_mat = confusion_matrix(y_test, predictions)

    print(f'Accuracy: {accuracy}')
    print(f'Confusion Matrix:\n{confusion_mat}')

# Main Function
def main():
    # Generate Synthetic Dataset with 1000 samples
    synthetic_data = generate_synthetic_data(1000)

    # Split the dataset into features (X) and target variable (y)
    X = synthetic_data.drop('Runoff_Volume', axis=1)
    y = synthetic_data['Runoff_Volume']

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the machine learning model
    model = train_model(X_train, y_train)

    # Evaluate the model
    evaluate_model(model, X_test, y_test)

# Run the main function
if __name__ == "__main__":
    main()


Accuracy: 0.78
Confusion Matrix:
[[152   8]
 [ 36   4]]


In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

# Generate Synthetic Dataset
def generate_synthetic_data(num_samples):
    np.random.seed(42)
    rainfall = np.random.uniform(0, 100, num_samples)
    atmospheric_pressure = np.random.uniform(800, 1200, num_samples)
    soil_absorption = np.random.uniform(0, 1, num_samples)
    runoff_volume = np.random.choice([0, 1], size=num_samples, p=[0.8, 0.2])

    synthetic_data = pd.DataFrame({
        'Rainfall': rainfall,
        'Atmospheric_Pressure': atmospheric_pressure,
        'Soil_Absorption': soil_absorption,
        'Runoff_Volume': runoff_volume
    })

    return synthetic_data

# Machine Learning Models
def train_gboost(X_train, y_train):
    model = GradientBoostingClassifier(random_state=42)
    model.fit(X_train, y_train)
    return model

def train_svm(X_train, y_train):
    model = SVC(random_state=42)
    model.fit(X_train, y_train)
    return model

# Evaluate Model
def evaluate_model(model, X_test, y_test):
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    confusion_mat = confusion_matrix(y_test, predictions)

    print(f'Accuracy: {accuracy}')
    print(f'Confusion Matrix:\n{confusion_mat}')
    return accuracy

# Main Function
def main():
    # Generate Synthetic Dataset with 1000 samples
    synthetic_data = generate_synthetic_data(1000)

    # Split the dataset into features (X) and target variable (y)
    X = synthetic_data.drop('Runoff_Volume', axis=1)
    y = synthetic_data['Runoff_Volume']

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Feature Scaling (important for algorithms like SVM)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Train Gradient Boosting Classifier
    print("Gradient Boosting Classifier:")
    gboost_model = train_gboost(X_train, y_train)
    gboost_accuracy = evaluate_model(gboost_model, X_test, y_test)

    # Train SVM Classifier
    print("\nSVM Classifier:")
    svm_model = train_svm(X_train_scaled, y_train)
    svm_accuracy = evaluate_model(svm_model, X_test_scaled, y_test)

    return gboost_accuracy, svm_accuracy

# Run the main function
main()


Gradient Boosting Classifier:
Accuracy: 0.765
Confusion Matrix:
[[152   8]
 [ 39   1]]

SVM Classifier:
Accuracy: 0.8
Confusion Matrix:
[[160   0]
 [ 40   0]]


(0.765, 0.8)